### ISSUE TITLE
Remove the unused current configuration tab@2

### ISSUE THREAD

**Issue by Highlife1911** [HPI-SWA-Teaching/SWT15-Project-06#11]
As a User i don't want to see a dead window.

**Comment by chistopher** [comment]
is der save current button noch sinnvoll?

**Comment by Highlife1911** [comment]
Nein, der kann auch rausgenommen werden. Eröffne dafür bitte eine neue user story und buche den entsprechenden Aufwand für die Änderung mit @ also 'User Story: Remove Unused Button in Setup Menu@1' oder so ähnlich.

Auch sollen wir die User Stories noch nicht selbst schließen, sondern nur in beisein des Kunden.
